synonyms = [['additional deductions', 'Additional deductions', 'Additional Deductions (from Net Income)', 'Additional deductions (from net income)', 'additional deductions (from net income)']
,['adoption expenses', 'Adoption expenses']
,['annuity income', 'Annuity income']
,['age amount', 'Age amount', 'Age Amount']
,['donations and gifts', 'Donations and Gifts', 'Charitable donations &amp; gov. gifts', 'Charitable donations/Government gif', 'allowable charitable donations and government gifts', 'Allowable charitable donations and government gifts', 'charitable, cultural, ecological and gov donations', 'charitable donations,cultural, ecological, gov']
,['alternative minimum tax payable', 'Alternative minimum tax payable']
,['amount for children 17 and under', 'Amount for children 17 and under']
,['amount for eligible dependant', 'Amount for eligible dependant']
,['amount for infirm dependants age 18 or older', 'Amount for infirm dependants age 18 or older', 'Amount for infirm dependents age 18 or older']
,['amounts transferred from spouse or common-law partner', 'Amounts transferred from spouse or common-law partner', 'Amounts transferred from spouse', 'Amounts Transferred from Spouse', 'amounts transferred from spouse']
,['annual union, professional, or like dues', 'Annual union, professional, or like dues', 'Annual Union, Professional, or Like Dues', 'Union and Professional Dues', 'Union and professional dues']
,['basic federal tax', 'Basic federal tax', 'Basic Federal Tax']
,['Federal tax']
,['basic personal amount', 'Basic personal amount']
,['business investment loss', 'Business investment loss']
,['CPP or QPP benefits', 'Canada Pension Plan (CPP) or Quebec Pension Plan (QPP) benefits', 'CPP or QPP Benefits', 'cpp or qpp benefits']
,['CPP or QPP contributions on employment', 'CPP or QPP contributions through employment', 'CPP or QPP contributions employment']
,['CPP or QPP contributions', 'cpp or qpp contributions', 'CPP or QPP Contributions']
,['CPP or QPP contributions on self-employment', 'CPP or QPP contributions on self-employment and other earnings', 'CPP or QPP contributions self-employment and other eligible earnings', 'CPP or QPP contributions on self-employment or other earnings', 'CPP or QPP contributions through self-employment', 'CPP or QPP contributions self-employment', 'CPP or QPP contributions on self-employed earnings', 'CPP/QPP contrib. on self-empl./other earning', 'cpp/qpp contrib. on self-empl./other earning']
,['CPP contributions on self-employment', 'CPP contributions payable on self-employment and other earnings', 'CPP Contr. On Self Employment', 'cpp contrib. on self-employ. earning', 'CPP contrib. on self-employ. earning']
,['Canada employment amount', 'Canada Employment Amount', 'canada employment amount']
,['Canadian Forces personnel and police deduction']
,['capital gains deduction', 'Capital gains deduction', 'Capital Gains Deduction']
,['caregiver amount', 'Caregiver amount']
,['carrying charges and interest expenses', 'Carrying charges and interest expenses', 'Carrying Charges & Interest Expenses']
,['child care expenses', 'Child care expenses', 'Child Care Expenses']
,["children's arts amount", "Children's arts amount"]
,["children's fitness amount", "Children's fitness amount", "Children's Fitness Amount"]
,['clergy residence deduction', 'Clergy residence deduction', "Cleric's residence deduction"]
,['commissions (from employment)', 'Commissions (from employment)', 'Commissions (from Employment)']
,['deduction for elected split-pension amount', 'Deduction for elected split-pension amount']
,['deduction for PPIP premiums on self-employment income', 'Deduction for PPIP premiums on self-employment income', 'Deduction for provincial parental insurance plan (PPIP) premiums on self-empl', 'Deductions for provincial parental insurance plan (PPIP) premiums on self-emplo']
,['deductions for CPP/QPP contributions on self-employment and other earnings', 'Deductions for CPP/QPP contributions on self-employment and other earnings', 'Deductions for CPP/QPP contributions on self-employment/other earnings', 'Deductions for CPP or QPP contributions on self-employment and other earnings']
,['disability amount', 'Disability amount', 'Disability and Caregiver Amounts']
,['disability amount transferred from a dependant', 'Disability amount transferred from a dependant', 'Disability amount transferred from a dependent']
,['disability supports deductions', 'Disability supports deductions']
,['education amounts and interest', 'Education Amounts and Interest']
,['elected split-pension amount', 'Elected split-pension amount']
,['eligible cultural and ecological gifts', 'Eligible cultural and ecological gifts', 'Eligible cultural, ecological gifts', 'Cultural and ecological gifts']
,['employee home relocation loan deduction', 'Employee home relocation loan deduction']
,['EI benefits', 'Employment Insurance and other benefits', 'Employment Insurance benefits', 'Employment Insurance Benefits', 'Employment Insurance and Other Benefits', 'employment insurance benefits']
,['EI premiums', 'Employment Insurance premiums', 'Employment Insurance Premiums', 'employment insurance premiums']
,['EI premiums payable on self-employment', 'Employment Insurance premiums payable on self-employment', 'Employment\xa0 Insurance premiums payable on self-employment and other eligible']
,['EI premiums on self-employment and other eligible earnings', 'Employment Insurance premiums on self-employment and other eligible earnings']
,['employment income', 'Employment income', 'Employment Income']
,['exploration and development expenses', 'Exploration and development expenses']
,['farming/fishing losses of prior years', 'Farming/fishing losses of prior years']
,['federal foreign tax credit', 'Federal foreign tax credit', 'Federal Foreign Tax Credit']
,['federal political contribution tax credit', 'Federal political contribution tax credit', 'Federal Political contribution tax credit', 'Federal political contribution tax  credit']
,['federal dividend tax credit', 'Federal dividend tax credit', 'Fed. dividend tax credit', 'Federal Dividend Tax Credit', 'Dividend tax credit', 'fed. dividend tax credit']
,["home buyers' amount", "Home buyers' amount"]
,['home renovation expenses', 'Home renovation expenses']
,['interest and other investment income', 'Interest and other investment income', 'Investment income', 'Interest and Other Investment Income', 'Investment Income and Other Investment Income', 'Investment income', 'interest,other invest. income', 'interest &amp; other invest. income']
,['interest paid on student loans', 'Interest paid on student loans', 'Interest paid on student loan']
,['investment tax credit', 'Investment tax credit', 'Investment Tax Credit']
,['labour-sponsored funds tax credit', 'Labour-sponsored funds tax credit']
,['limited partnership losses of other years', 'Limited partnership losses of other years']
,['losses from other years', 'Losses from Other Years', 'Losses from other years', 'losses from other years']
,['medical expenses', 'Medical expenses', 'allowable portion of medical expenses', 'Allowable portion of medical expenses',  'Allowable Amount of Medical Expenses', 'Allowable Portion of Medical Expenses', 'Allowable amt. of med. expenses', 'Allowable portion of medical expens', 'allowable amt. of med. expenses']
,['minimum tax carryover', 'Minimum tax carryover']
,['moving expenses', 'Moving expenses']
,['net business income', 'Net business income', 'Net Business Income']
,['net capital losses of other years', 'Net capital losses of other years']
,['net commission income', 'Net commission income', 'Net Commission Income']
,['net farming income', 'Net farming income', 'Net Farming Income', ]
,['net federal supplements', 'Net federal supplements']
,['net federal tax', 'Net federal tax', 'Net Federal Tax']
,['net fishing income', 'Net fishing income', 'Net Fishing Income']
,['net income after adjustments', 'Net income after adjustments', 'Net Income after Adjustments', 'Net income after adjustment', 'net income after adjustment', 'Net Income']
,['net partnership income', 'Net partnership income', 'Net partnership income (Limited or non-active partners only)']
,['net professional income', 'Net professional income', 'Net Professional Income']
,['net provincial or territorial tax', 'Net provincial or territorial tax', 'Net provincial tax', 'Net Provincial Tax', 'Net Provincial Tax or Territorial Tax', 'Net Provincial or Territorial Tax', 'net provincial tax']
,['net rental income', 'Net rental income', 'Net Rental Income']
,['non-capital losses of other years', 'Non-capital losses of other years']
,['northern residents deductions', 'Northern residents deductions']
,['number of non-taxable returns', 'Number of non-taxable returns', 'Number of Non-Taxable Returns']
,['number of taxable returns', 'Number of taxable returns', 'Number of Taxable Returns']
,['Old Age Security Pension', 'Old Age Security pension', 'Old Age Security pension (OASP)', 'old age security pension']
,['other deductions', 'Other deductions', 'Other Deductions (from Total Income)', 'Other deductions (from total income)', 'other deductions (from total income)']
,['other employment expenses', 'Other employment expenses', 'Other Employment Expenses']
,['other employment income', 'Other employment income', 'Other Employment Income']
,['other income', 'Other income', 'Other Income']
,['other payments deductions', 'Other payments deductions']
,['other pensions or superannuation', 'Other pensions or superannuation', 'Other Pensions or Superannuation']
,['overseas employment tax credit', 'Overseas employment tax credit']
,['other federal non-refundable tax credits', 'Other Federal Non-Refundable Tax Credits']
,['PPIP premiums paid', 'Provincial Parental Insurance Plan (PPIP) premiums paid', 'Provincial Parental Insurance Plan', 'Provincial Parental Insurance Plan Premiums']
,['PPIP premiums payable on employment income']
,['PPIP premiums payable on self-employment income']
,['pension income amount', 'Pension income amount', 'Pension Income Amount', 'Eligible pension income amount']
,['public transit amount', 'Public transit amount', 'Public Transit Passes Amount', 'public transit passes amount']
,['RRSP deduction', 'Registered Retirement Savings Plan deduction',  'RRSP contributions', 'rrsp contributions', 'Registered Retirement Savings Plan Contributions']
,['RRSP income', 'Registered Retirement Savings Plan (RRSP) income', 'Registered Retirement Savings Plan income', 'Registered retirement savings plan income (RRSP)', 'rrsp income', 'Registered Retirement Savings Plan Income']
,['Registered Disability Savings Plan income', 'Registered disability savings plan income', 'Registered disability savings plan (RDSP) income', 'Registered disability savings plan income (RDSP)', 'RDSP income','Registered Disability Savings Plan Income']
,['Registered Pension Plan contributions', 'Registered pension plan contributions', 'Registered pension plan (RPP) contributions', 'Registered pension plan contributions (RPP)', 'RPP contributions',  'Registered Pension Plan Contributions', 'Registered Pension Plan deduction', 'RPP deduction', 'rpp deduction']
,['Saskatchewan Pension Plan deduction', 'Saskatchewan Pension Plan (SPP) deduction']
,['security options deductions', 'Security options deductions']
,['social benefits repayment', 'Social benefits repayment', 'Social Benefits repayment', 'Social Benefits Repayment']
,['social assistance payments', 'Social assistance payments']
,['spouse or common-law partner amount', 'Spouse or common-law partner amount', 'Spousal or equivalent-to-spouse amount']
,['spouse, eligible dependant and adoption amount', 'spouse,elig. depend.,adoption amt.', 'Spouse &amp; elig. depend. &amp; adoption amt.']
,['support payments made', 'Support payments made']
,['support payments received', 'Support payments received']
,['tax-exempt income','Tax Exempt Income','Tax-exempt income']
,['taxable amount of dividends', 'Taxable amount of dividends', 'Taxable Amount of Dividends', 'taxable amount of dividends from taxable Canadian corporations', 'Taxable amount of dividends from taxable Canadian corporations']
,['taxable capital gains', 'Taxable capital gains', 'Taxable Capital Gains']
,['taxable income assessed', 'Taxable income assessed', 'Taxable Income Assessed']
,['total deductions before adjustments', 'Total deductions before adjustments', 'Total deduction before adjustment', 'Total deduction before adjustments', 'total deduction before adjustment', 'Total Deductions before Adjustments', 'Total Deductions']
,['total deductions from net income', 'Total deductions from net income', 'Total Deductions (from Net Income)', 'Total deductions (from Net income)', 'Total deductions (from net income)', 'Total Deductions from Net Income', 'total deductions (from net income)']
,['total federal non-refundable tax credits', 'Total federal non-refundable tax credits', 'Total Federal Non-Refundable Tax Credits', 'total non-refundable tax credits', 'Total Non-Refundable Tax Credits', 'Total non-refundable tax credits']
,['total income assessed', 'Total income assessed', 'Total Income Assessed']
,['Net income before adjustments']
,['total number of returns', 'Total number of returns', 'Total Number of Returns']
,['total tax credit on donations and gifts', 'Total tax credit on donations and gifts', 'Tax Credits on Donations and Gifts', 'Total Tax Credit on Donations', 'Total tax credits on donations', 'Donations &amp; gifts', 'donations,gifts']
,['total tax credits on personal amounts', 'Total tax credits on personal amounts', 'Total Tax Credits on Personal Amounts',  'Total tax credits on allowed amount', 'net tax credits on personal amounts', 'Net Tax Credits on Personal Amounts']
,['total tax credits', 'Total tax credits']
,['total tax payable', 'Total tax payable',  'Total Tax Payable']
,['tuition, education, and textbook amounts', 'Tuition, education, and textbook amounts', 'Tuition and education amounts', 'tuition and education amounts', 'Tuition fees and education amount']
,['tuition, education, and textbook amounts transferred from a child', 'Tuition, education, and textbook amounts transferred from a child']
,['tuition, education, textbook amounts and interest on student loans', 'Tuition, Education, Textbook amounts & Interest on student loans']
,['Universal Child Care Benefit', 'Universal Child Care Benefit (UCCB)', 'universal child care benefits']
,['Universal Child Care Benefit repayment']
,["volunteer firefighters' amount", "Volunteer firefighters' amount"]
,["workers' compensation benefits", "Workers' compensation benefits"]
,['Yukon first nations tax']
]