synonyms = [['additional deductions', 'Additional deductions']
,['adoption expenses', 'Adoption expenses']
,['age amount', 'Age amount']
,['allowable charitable donations and government gifts', 'Allowable charitable donations and government gifts']
,['allowable portion of medical expenses', 'Allowable portion of medical expenses']
,['alternative minimum tax payable', 'Alternative minimum tax payable']
,['amount for children 17 and under', 'Amount for children 17 and under']
,['amount for eligible dependant', 'Amount for eligible dependant']
,['amount for infirm dependants age 18 or older', 'Amount for infirm dependants age 18 or older', 'Amount for infirm dependents age 18 or older']
,['amounts transferred from spouse or common-law partner', 'Amounts transferred from spouse or common-law partner', 'Amounts transferred from spouse']
,['annual union, professional, or like dues', 'Annual union, professional, or like dues']
,['basic federal tax', 'Basic federal tax']
,['basic personal amount', 'Basic personal amount']
,['business investment loss', 'Business investment loss']
,['CPP contributions on self-employment']
,['CPP contributions payable on self-employment and other earnings']
,['CPP or QPP benefits', 'Canada Pension Plan (CPP) or Quebec Pension Plan (QPP) benefits']
,['CPP or QPP contributions through employment', 'CPP or QPP contributions employment']
,['CPP or QPP contributions through self-employment', 'CPP or QPP contributions self-employment', 'CPP or QPP contributions self-employment and other eligible earnings', 'CPP or QPP contributions on self-employment and other earnings']
,['Canada employment amount']
,['Canadian Forces personnel and police deduction']
,['capital gains deduction', 'Capital gains deduction']
,['caregiver amount', 'Caregiver amount']
,['carrying charges and interest expenses', 'Carrying charges and interest expenses']
,['child care expenses', 'Child care expenses']
,["children's arts amount", "Children's arts amount"]
,["children's fitness amount", "Children's fitness amount"]
,['clergy residence deduction', 'Clergy residence deduction']
,['commissions (from employment)', 'Commissions (from employment)']
,['deduction for elected split-pension amount', 'Deduction for elected split-pension amount']
,['deduction for PPIP premiums on self-employment income', 'Deduction for PPIP premiums on self-employment income', 'Deduction for provincial parental insurance plan (PPIP) premiums on self-empl', 'Deductions for provincial parental insurance plan (PPIP) premiums on self-emplo']
,['deductions for CPP/QPP contributions on self-employment and other earnings', 'Deductions for CPP/QPP contributions on self-employment and other earnings', 'Deductions for CPP/QPP contributions on self-employment/other earnings', 'Deductions for CPP or QPP contributions on self-employment and other earnings']
,['disability amount', 'Disability amount']
,['disability amount transferred from a dependant', 'Disability amount transferred from a dependant', 'Disability amount transferred from a dependent']
,['disability supports deductions', 'Disability supports deductions']
,['elected split-pension amount', 'Elected split-pension amount']
,['eligible cultural and ecological gifts', 'Eligible cultural and ecological gifts', 'Eligible cultural, ecological gifts']
,['employee home relocation loan deduction', 'Employee home relocation loan deduction']
,['EI benefits', 'Employment Insurance and other benefits', 'Employment Insurance benefits']
,['EI premiums', 'Employment Insurance premiums']
,['EI premiums payable on self-employment', 'Employment Insurance premiums on self-employment and other eligible earnings', 'Employment\xa0 Insurance premiums payable on self-employment and other eligible', 'Employment Insurance premiums payable on self-employment']
,['employment income', 'Employment income']
,['exploration and development expenses', 'Exploration and development expenses']
,['farming/fishing losses of prior years', 'Farming/fishing losses of prior years']
,['federal foreign tax credit', 'Federal foreign tax credit', 'Federal Foreign Tax Credit']
,['federal political contribution tax credit', 'Federal political contribution tax credit', 'Federal Political contribution tax credit', 'Federal political contribution tax  credit']
,['federal dividend tax credit', 'Federal dividend tax credit']
,["home buyers' amount", "Home buyers' amount"]
,['home renovation expenses', 'Home renovation expenses']
,['interest and other investment income', 'Interest and other investment income']
,['interest paid on student loans', 'Interest paid on student loans']
,['investment tax credit', 'Investment tax credit', 'Investment Tax Credit']
,['labour-sponsored funds tax credit', 'Labour-sponsored funds tax credit']
,['limited partnership losses of other years', 'Limited partnership losses of other years']
,['medical expenses', 'Medical expenses']
,['minimum tax carryover', 'Minimum tax carryover']
,['moving expenses', 'Moving expenses']
,['net business income', 'Net business income']
,['net capital losses of other years', 'Net capital losses of other years']
,['net commission income', 'Net commission income']
,['net farming income', 'Net farming income']
,['net federal supplements', 'Net federal supplements']
,['net federal tax', 'Net federal tax']
,['net fishing income', 'Net fishing income']
,['net income after adjustments', 'Net income after adjustments']
,['net partnership income', 'Net partnership income', 'Net partnership income (Limited or non-active partners only)']
,['net professional income', 'Net professional income']
,['net provincial or territorial tax', 'Net provincial or territorial tax', 'Net provincial tax', 'Net Provincial Tax']
,['net rental income', 'Net rental income']
,['non-capital losses of other years', 'Non-capital losses of other years']
,['northern residents deductions', 'Northern residents deductions']
,['number of non-taxable returns', 'Number of non-taxable returns']
,['number of taxable returns', 'Number of taxable returns']
,['Old Age Security Pension', 'Old Age Security pension', 'Old Age Security pension (OASP)']
,['other deductions', 'Other deductions']
,['other employment expenses', 'Other employment expenses']
,['other employment income', 'Other employment income']
,['other income', 'Other income']
,['other payments deductions', 'Other payments deductions']
,['other pensions or superannuation', 'Other pensions or superannuation']
,['overseas employment tax credit', 'Overseas employment tax credit']
,['PPIP premiums paid', 'Provincial Parental Insurance Plan (PPIP) premiums paid']
,['PPIP premiums payable on employment income']
,['PPIP premiums payable on self-employment income']
,['pension income amount', 'Pension income amount']
,['public transit amount', 'Public transit amount']
,['RRSP deduction', 'Registered Retirement Savings Plan deduction']
,['RRSP income', 'Registered Retirement Savings Plan (RRSP) income', 'Registered Retirement Savings Plan income', 'Registered retirement savings plan income (RRSP)']
,['Registered Disability Savings Plan income', 'Registered disability savings plan income', 'Registered disability savings plan (RDSP) income', 'Registered disability savings plan income (RDSP)', 'RDSP income']
,['Registered Pension Plan contributions', 'Registered pension plan contributions', 'Registered pension plan (RPP) contributions', 'Registered pension plan contributions (RPP)']
,['Saskatchewan Pension Plan deduction', 'Saskatchewan Pension Plan (SPP) deduction']
,['security options deductions', 'Security options deductions']
,['social benefits repayment', 'Social benefits repayment', 'Social Benefits repayment']
,['social assistance payments', 'Social assistance payments']
,['spouse or common-law partner amount', 'Spouse or common-law partner amount']
,['support payments made', 'Support payments made']
,['support payments received', 'Support payments received']
,['taxable amount of dividends', 'Taxable amount of dividends']
,['taxable amount of dividends from taxable Canadian corporations', 'Taxable amount of dividends from taxable Canadian corporations']
,['taxable capital gains', 'Taxable capital gains']
,['taxable income assessed', 'Taxable income assessed']
,['total deductions before adjustments', 'Total deductions before adjustments']
,['total deductions from net income', 'Total deductions from net income']
,['total federal non-refundable tax credits', 'Total federal non-refundable tax credits']
,['total income assessed', 'Total income assessed']
,['total number of returns', 'Total number of returns']
,['total tax credit on donations and gifts', 'Total tax credit on donations and gifts']
,['total tax credits on personal amounts', 'Total tax credits on personal amounts']
,['total tax payable', 'Total tax payable']
,['tuition, education, and textbook amounts', 'Tuition, education, and textbook amounts']
,['tuition, education, and textbook amounts transferred from a child', 'Tuition, education, and textbook amounts transferred from a child']
,['Universal Child Care Benefit', 'Universal Child Care Benefit (UCCB)']
,['Universal Child Care Benefit repayment']
,["volunteer firefighters' amount", "Volunteer firefighters' amount"]
,["workers' compensation benefits", "Workers' compensation benefits"]
,['Yukon first nations tax']
]