synonyms = [['Additional deductions']
,['Adoption expenses']
,['Age amount']
,['Allowable charitable donations and government gifts']
,['Allowable portion of medical expenses']
,['Alternative minimum tax payable']
,['Amount for children 17 and under']
,['Amount for eligible dependant']
,['Amount for infirm dependants age 18 or older', 'Amount for infirm dependents age 18 or older']
,['Amounts transferred from spouse or common-law partner', 'Amounts transferred from spouse']
,['Annual union, professional, or like dues']
,['Basic federal tax']
,['Basic personal amount']
,['Business investment loss']
,['CPP contributions on self-employment']
,['CPP contributions payable on self-employment and other earnings']
,['CPP or QPP benefits', 'Canada Pension Plan (CPP) or Quebec Pension Plan (QPP) benefits']
,['CPP or QPP contributions through employment', 'CPP or QPP contributions employment']
,['CPP or QPP contributions through self-employment', 'CPP or QPP contributions self-employment', 'CPP or QPP contributions self-employment and other eligible earnings', 'CPP or QPP contributions on self-employment and other earnings']
,['Canada employment amount']
,['Canadian Forces personnel and police deduction']
,['Capital gains deduction']
,['Caregiver amount']
,['Carrying charges and interest expenses']
,['Child care expenses']
,["Children's arts amount"]
,["Children's fitness amount"]
,['Clergy residence deduction']
,['Commissions (from employment)']
,['Deduction for elected split-pension amount']
,['Deduction for PPIP premiums on self-employment income', 'Deduction for provincial parental insurance plan (PPIP) premiums on self-empl', 'Deductions for provincial parental insurance plan (PPIP) premiums on self-emplo']
,['Deductions for CPP/QPP contributions on self-employment and other earnings', 'Deductions for CPP/QPP contributions on self-employment/other earnings', 'Deductions for CPP or QPP contributions on self-employment and other earnings']
,['Disability amount']
,['Disability amount transferred from a dependant', 'Disability amount transferred from a dependent']
,['Disability supports deductions']
,['Elected split-pension amount']
,['Eligible cultural and ecological gifts', 'Eligible cultural, ecological gifts']
,['Employee home relocation loan deduction']
,['EI benefits', 'Employment Insurance and other benefits', 'Employment Insurance benefits']
,['EI premiums', 'Employment Insurance premiums']
,['EI premiums payable on self-employment', 'Employment Insurance premiums on self-employment and other eligible earnings', 'Employment\xa0 Insurance premiums payable on self-employment and other eligible', 'Employment Insurance premiums payable on self-employment']
,['Employment income']
,['Exploration and development expenses']
,['Farming/fishing losses of prior years']
,['Federal foreign tax credit', 'Federal Foreign Tax Credit']
,['Federal political contribution tax credit', 'Federal Political contribution tax credit', 'Federal political contribution tax  credit']
,['Federal dividend tax credit']
,["Home buyers' amount"]
,['Home renovation expenses']
,['Interest and other investment income']
,['Interest paid on student loans']
,['Investment tax credit', 'Investment Tax Credit']
,['Labour-sponsored funds tax credit']
,['Limited partnership losses of other years']
,['Medical expenses']
,['Minimum tax carryover']
,['Moving expenses']
,['Net business income']
,['Net capital losses of other years']
,['Net commission income']
,['Net farming income']
,['Net federal supplements']
,['Net federal tax']
,['Net fishing income']
,['Net income after adjustments']
,['Net partnership income', 'Net partnership income (Limited or non-active partners only)']
,['Net professional income']
,['Net provincial or territorial tax', 'Net provincial tax', 'Net Provincial Tax']
,['Net rental income']
,['Non-capital losses of other years']
,['Northern residents deductions']
,['Number of non-taxable returns']
,['Number of taxable returns']
,['Old Age Security Pension', 'Old Age Security pension', 'Old Age Security pension (OASP)']
,['Other deductions']
,['Other employment expenses']
,['Other employment income']
,['Other income']
,['Other payments deductions']
,['Other pensions or superannuation']
,['Overseas employment tax credit']
,['PPIP premiums paid', 'Provincial Parental Insurance Plan (PPIP) premiums paid']
,['PPIP premiums payable on employment income']
,['PPIP premiums payable on self-employment income']
,['Pension income amount']
,['Public transit amount']
,['RRSP deduction', 'Registered Retirement Savings Plan deduction']
,['RRSP income', 'Registered Retirement Savings Plan (RRSP) income', 'Registered Retirement Savings Plan income', 'Registered retirement savings plan income (RRSP)']
,['Registered Disability Savings Plan income', 'Registered disability savings plan income', 'Registered disability savings plan (RDSP) income', 'Registered disability savings plan income (RDSP)', 'RDSP income']
,['Registered Pension Plan contributions', 'Registered pension plan contributions', 'Registered pension plan (RPP) contributions', 'Registered pension plan contributions (RPP)']
,['Saskatchewan Pension Plan deduction', 'Saskatchewan Pension Plan (SPP) deduction']
,['Security options deductions']
,['Social benefits repayment', 'Social Benefits repayment']
,['Social assistance payments']
,['Spouse or common-law partner amount']
,['Support payments made']
,['Support payments received']
,['Taxable amount of dividends']
,['Taxable amount of dividends from taxable Canadian corporations']
,['Taxable capital gains']
,['Taxable income assessed']
,['Total deductions before adjustments']
,['Total deductions from net income']
,['Total federal non-refundable tax credits']
,['Total income assessed']
,['Total number of returns']
,['Total tax credit on donations and gifts']
,['Total tax credits on personal amounts']
,['Total tax payable']
,['Tuition, education, and textbook amounts']
,['Tuition, education, and textbook amounts transferred from a child']
,['Universal Child Care Benefit', 'Universal Child Care Benefit (UCCB)']
,['Universal Child Care Benefit repayment']
,["Volunteer firefighters' amount"]
,["Workers' compensation benefits"]
,['Yukon first nations tax']
]