item_dict = [
['Number of taxable returns', 1],
['Number of non-taxable returns', 2],
['Total number of returns', 3],
['Employment income', 4],
['Commissions (from employment)', 5],
['Other employment income', 6],
['Old Age Security pension', 7],
['CPP or QPP benefits', 8],
['Other pensions or superannuation', 9],
['Employment Insurance benefits', 10],
['Taxable amount of dividends', 11],
['Investment income', 12],
['Annuity income', 13],
['Net rental income', 14],
['Taxable capital gains', 15],
['RRSP income', 16],
['Net business income', 17],
['Net professional income', 18],
['Net commission income', 19],
['Net farming income', 20],
['Net fishing income', 21],
['Tax-exempt income', 22],
['Other income', 23],
['Total income assessed', 24],
['RPP contributions', 25],
['RRSP contributions', 26],
['Union and professional dues', 27],
['Child care expenses', 28],
['Carrying charges and interest expenses', 29],
['CPP or QPP contributions on self-employment or other earnings', 30],
['Other employment expenses', 31],
["Cleric's residence deduction", 32],
['Other deductions (from total income)', 33],
['Total deduction before adjustments', 34],
['Net income before adjustments', 35],
['Social benefits repayment', 36],
['Net income after adjustment', 37],
['Capital gains deduction', 38],
['Additional deductions (from net income)', 39],
['Total deductions (from Net income)', 40],
['Taxable income assessed', 41],
['Basic personal amount', 42],
['Age amount', 43],
['Spousal or equivalent-to-spouse amount', 44],
['CPP or QPP contributions', 45],
['Employment Insurance premiums', 46],
['Eligible pension income amount', 47],
['Caregiver amount', 48],
['Disability amount', 49],
['Tuition fees and education amount', 50],
['Interest paid on student loan', 51],
['Amounts transferred from spouse', 52],
['Allowable portion of medical expens', 53],
['Total tax credits on allowed amount', 54],
['Charitable donations/Government gif', 55],
['Cultural and ecological gifts', 56],
['Total tax credits on donations',  57],
['Total non-refundable tax credits',  58],
['Basic federal tax', 59],
['Dividend tax credit', 60],
['Federal tax', 61],
['Net federal tax', 62],
['Net provincial tax',  63],
['Total tax payable', 64]
]